name: pipeline 

on:
  push:
    branches: [ main ]

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image_API
        run: docker build -t my-api:latest ./api

      - name: Build Database_image
        run: docker build -t devsecops-pipeline-python-api-db_beer:latest ./sql

 
  deploy_stack:
    runs-on: ubuntu-latest
    needs: build_images 
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Deploiement sur Docker Swarm
        run: |
          echo "Initialisation du déploiement Swarm..."
          docker stack config -c docker-stack.yml